
USE ROLE SYSADMIN;

-- CREATE WAREHOUSE AND DATABASES
CREATE OR REPLACE warehouse transforming;
CREATE OR REPLACE warehouse analytics;
CREATE OR REPLACE DATABASE raw;
CREATE OR REPLACE DATABASE transform;
CREATE OR REPLACE DATABASE analytics;
CREATE OR REPLACE schema raw.nmi;
CREATE OR REPLACE schema transform.nmi;
CREATE OR REPLACE schema analytics.nmi;

USE ROLE SECURITYADMIN;

--  CREATE USER AND ROLES
CREATE OR REPLACE ROLE DEV_ROLE COMMENT='DEV_ROLE';
GRANT ROLE DEV_ROLE TO ROLE SYSADMIN;

CREATE OR REPLACE USER DEV_USER PASSWORD='xxxxxx'
	DEFAULT_ROLE=DEV_ROLE
	DEFAULT_WAREHOUSE=DEV_WH
	COMMENT='DEV User';
    
GRANT ROLE DEV_ROLE TO USER DEV_USER;

-- Grant privileges to role
USE ROLE ACCOUNTADMIN;

GRANT CREATE DATABASE ON ACCOUNT TO ROLE DEV_ROLE;

/*---------------------------------------------------------------------------
Next we will create a virtual warehouse that will be used
---------------------------------------------------------------------------*/
USE ROLE SYSADMIN;
--Create Warehouse for dbt work
CREATE OR REPLACE WAREHOUSE DEV_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = true
  INITIALLY_SUSPENDED = TRUE;

GRANT ALL ON WAREHOUSE DEV_WH TO ROLE DEV_ROLE;

use database raw;
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO ROLE DEV_ROLE;

use database transform;
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO ROLE DEV_ROLE;

use database analytics;
GRANT CREATE SCHEMA, MODIFY ON DATABASE ANALYTICS TO ROLE DEV_ROLE;
GRANT ROLE DEV_ROLE TO USER DEV_USER;